title: Poohnilista
author: Hugo Cattarucci Bot√≥s
github:
  is_project_page: false
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - articles.md
  - classicalgeometry.md
  - exposition.md
  - oqehgeometria.md
  - pooh.jpg

theme: jekyll-theme-slate