author: Hugo Cattarucci Bot√≥s
name: Poohnilista
title: null
plugins:
  - jekyll-paginate
  - jekyll-sitemap
include:
  - README.md
  - articles.md
  - classicalgeometry.md
  - exposition.md
  - oqehgeometria.md
  - pooh.jpg
gems: 
      - jekyll-sitemap
