author: Hugo Cattarucci Bot√≥s
title: Poohnilista
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - articles.md
  - classicalgeometry.md
  - exposition.md
  - oqehgeometria.md
  - pooh.jpg
